In [1]:
# Importing packages 

import pandas as pd
import numpy as np

In [2]:
# Reading data in from Worlds File

raw_world_data = pd.read_csv('./2017-worlds-match-data-OraclesElixir-2017-11-05.csv')
print(raw_world_data.shape)
raw_world_data.head()

(1428, 92)

,gameid,url,league,split,date,week,game,patchno,playerid,side,...,cspm,goldat10,oppgoldat10,gdat10,goldat15,oppgoldat15,gdat15,xpat10,oppxpat10,xpdat10
0,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,1,Blue,...,6.063604,3349,3153,196,4880,4788,92,5025,4556,469
1,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,2,Blue,...,3.625442,2956,2667,289,4323,4234,89,3318,3332,-14
2,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,3,Blue,...,9.222615,3140,3875,-735,5147,5799,-652,4592,5083,-491
3,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,4,Blue,...,9.180212,3142,3230,-88,5372,5176,196,3112,3081,31
4,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,5,Blue,...,0.318021,2533,2051,482,4256,3300,956,3053,2882,171

In [3]:
# Checking out our data 
raw_world_data.describe()

,gameid,date,patchno,playerid,gamelength,result,k,d,a,teamkills,...,cspm,goldat10,oppgoldat10,gdat10,goldat15,oppgoldat15,gdat15,xpat10,oppxpat10,xpdat10
count,1.428000e+03,1428.000000,1.428000e+03,1428.000000,1428.000000,1428.000000,1428.000000,1428.000000,1428.000000,1428.000000,...,1428.000000,1428.000000,1428.000000,1428.000000,1428.000000,1428.000000,1428.000000,1428.000000,1428.000000,1428.00000
mean,1.002365e+09,43017.109055,7.180000e+00,29.583333,35.070448,0.500000,3.250700,3.254902,8.501401,9.752101,...,10.582675,5077.022409,5077.022409,0.000000,8016.110644,8016.110644,0.000000,6059.015406,6059.015406,0.00000
std,3.209126e+04,11.398375,1.466008e-13,57.670664,8.816658,0.500175,4.263258,4.026995,10.803883,5.848247,...,10.042971,4577.370251,4577.370251,669.652407,7240.936995,7240.936995,1289.023865,5485.736971,5485.736971,584.31814
min,1.002290e+09,43001.001840,7.180000e+00,1.000000,20.866667,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.047923,1744.000000,1744.000000,-3765.000000,2629.000000,2629.000000,-7754.000000,1664.000000,1664.000000,-3247.00000
25%,1.002360e+09,43006.047620,7.180000e+00,3.750000,27.483333,0.000000,0.000000,1.000000,2.000000,6.000000,...,4.154415,2875.750000,2875.750000,-285.000000,4442.000000,4442.000000,-487.250000,3028.500000,3028.500000,-294.00000
50%,1.002380e+09,43016.175090,7.180000e+00,6.500000,33.183333,0.500000,2.000000,2.000000,5.000000,10.000000,...,8.440162,3209.000000,3209.000000,0.000000,5060.000000,5060.000000,0.000000,3797.000000,3797.000000,0.00000
75%,1.002390e+09,43023.150650,7.180000e+00,9.250000,40.350000,1.000000,4.000000,4.000000,9.000000,13.000000,...,10.217659,3563.500000,3563.500000,285.000000,5709.000000,5709.000000,487.250000,4817.250000,4817.250000,294.00000
max,1.002410e+09,43043.169930,7.180000e+00,200.000000,61.816667,1.000000,38.000000,38.000000,82.000000,38.000000,...,38.083183,18310.000000,18310.000000,3765.000000,28636.000000,28636.000000,7754.000000,20074.000000,20074.000000,3247.00000

In [4]:
# Since count is the same for all lets check to make sure there are no 
# out of bounds values

raw_world_data.isnull().any()

gameid                     False
url                        False
league                     False
split                      False
date                       False
week                       False
game                       False
patchno                    False
playerid                   False
side                       False
position                   False
player                     False
team                       False
champion                   False
ban1                       False
ban2                       False
ban3                       False
ban4                       False
ban5                       False
gamelength                 False
result                     False
k                          False
d                          False
a                          False
teamkills                  False
teamdeaths                 False
doubles                    False
triples                    False
quadras                    False
pentas                     False
                           ...
dmgtochampsperminute       False
dmgshare                   False
earnedgoldshare            False
wards                      False
wpm                        False
wardshare                  False
wardkills                  False
wcpm                       False
visionwards                False
visionwardbuys             False
visiblewardclearrate        True
invisiblewardclearrate     False
totalgold                  False
earnedgpm                  False
goldspent                  False
gspd                       False
minionkills                False
monsterkills               False
monsterkillsownjungle      False
monsterkillsenemyjungle    False
cspm                       False
goldat10                   False
oppgoldat10                False
gdat10                     False
goldat15                   False
oppgoldat15                False
gdat15                     False
xpat10                     False
oppxpat10                  False
xpdat10                    False
Length: 92, dtype: bool

In [5]:
# There was a null value in Visible ward clear rate. Lets see what that looks like

raw_world_data['visiblewardclearrate']

0
1
2
3
4
5
6
7
8
9
10      0.741935484
11      0.571428571
12
13
14
15
16
17
18
19
20
21
22      0.722222222
23            0.375
24
25
26
27
28
29
           ...
1398
1399
1400
1401
1402    0.789473684
1403    0.470588235
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414    0.828571429
1415    0.490909091
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426            0.6
1427            0.5
Name: visiblewardclearrate, Length: 1428, dtype: object

In [6]:
# This appears to be team values that are not player related so 
# All team rows have Team as position so lets select those
team_filter = raw_world_data['position'] == 'Team'
team_filter.head(20)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: position, dtype: bool

In [7]:
# Putting only team data in the team_data df
team_data = raw_world_data[team_filter]
team_data.head()

,gameid,url,league,split,date,week,game,patchno,playerid,side,...,cspm,goldat10,oppgoldat10,gdat10,goldat15,oppgoldat15,gdat15,xpat10,oppxpat10,xpdat10
10,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,100,Blue,...,28.409894,15120,14976,144,23978,23297,681,19100,18934,166
11,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,200,Red,...,29.088339,14976,15120,-144,23297,23978,-681,18934,19100,-166
22,1002360222,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.06067,1.1,2,7.18,100,Blue,...,30.644628,14473,14240,233,23162,22175,987,18245,17058,1187
23,1002360222,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.06067,1.1,2,7.18,200,Red,...,30.578512,14240,14473,-233,22175,23162,-987,17058,18245,-1187
34,1002360229,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.10113,1.1,3,7.18,100,Blue,...,31.722416,14338,14740,-402,21389,23582,-2193,18339,18461,-122

In [8]:
# Lets do the same but this time but with the player data 
player_filter = raw_world_data['position'] != 'Team'
player_data = raw_world_data[player_filter]
player_data.head()

,gameid,url,league,split,date,week,game,patchno,playerid,side,...,cspm,goldat10,oppgoldat10,gdat10,goldat15,oppgoldat15,gdat15,xpat10,oppxpat10,xpdat10
0,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,1,Blue,...,6.063604,3349,3153,196,4880,4788,92,5025,4556,469
1,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,2,Blue,...,3.625442,2956,2667,289,4323,4234,89,3318,3332,-14
2,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,3,Blue,...,9.222615,3140,3875,-735,5147,5799,-652,4592,5083,-491
3,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,4,Blue,...,9.180212,3142,3230,-88,5372,5176,196,3112,3081,31
4,1002360213,http://matchhistory.na.leagueoflegends.com/en/...,WC,2017-W,43001.00184,1.1,1,7.18,5,Blue,...,0.318021,2533,2051,482,4256,3300,956,3053,2882,171

In [10]:
# Lets delete some useless data
player_data.drop(player_data.columns[1:9], axis = 1)

,gameid,side,position,player,team,champion,ban1,ban2,ban3,ban4,...,cspm,goldat10,oppgoldat10,gdat10,goldat15,oppgoldat15,gdat15,xpat10,oppxpat10,xpdat10
0,1002360213,Blue,Top,957,Team WE,Cho'gath,Rek'Sai,Alistar,Tristana,Karma,...,6.063604,3349,3153,196,4880,4788,92,5025,4556,469
1,1002360213,Blue,Jungle,Condi,Team WE,Gragas,Rek'Sai,Alistar,Tristana,Karma,...,3.625442,2956,2667,289,4323,4234,89,3318,3332,-14
2,1002360213,Blue,Middle,xiye,Team WE,Corki,Rek'Sai,Alistar,Tristana,Karma,...,9.222615,3140,3875,-735,5147,5799,-652,4592,5083,-491
3,1002360213,Blue,ADC,Mystic,Team WE,Xayah,Rek'Sai,Alistar,Tristana,Karma,...,9.180212,3142,3230,-88,5372,5176,196,3112,3081,31
4,1002360213,Blue,Support,Ben,Team WE,Janna,Rek'Sai,Alistar,Tristana,Karma,...,0.318021,2533,2051,482,4256,3300,956,3053,2882,171
5,1002360213,Red,Top,Jirall,Lyon Gaming,Maokai,Kalista,Sejuani,Jarvan IV,LeBlanc,...,6.127208,3153,3349,-196,4788,4880,-92,4556,5025,-469
6,1002360213,Red,Jungle,Oddie,Lyon Gaming,Lee Sin,Kalista,Sejuani,Jarvan IV,LeBlanc,...,3.180212,2667,2956,-289,4234,4323,-89,3332,3318,14
7,1002360213,Red,Middle,Seiya,Lyon Gaming,Syndra,Kalista,Sejuani,Jarvan IV,LeBlanc,...,8.544170,3875,3140,735,5799,5147,652,5083,4592,491
8,1002360213,Red,ADC,WhiteLotus,Lyon Gaming,Kog'Maw,Kalista,Sejuani,Jarvan IV,LeBlanc,...,9.752650,3230,3142,88,5176,5372,-196,3081,3112,-31
9,1002360213,Red,Support,Genthix,Lyon Gaming,Braum,Kalista,Sejuani,Jarvan IV,LeBlanc,...,1.484099,2051,2533,-482,3300,4256,-956,2882,3053,-171
12,1002360222,Blue,Top,Impact,Cloud9,Galio,Tristana,Sejuani,Kalista,Trundle,...,6.909091,3000,3187,-187,4852,4534,318,4534,4695,-161
13,1002360222,Blue,Jungle,Contractz,Cloud9,Rek'Sai,Tristana,Sejuani,Kalista,Trundle,...,5.256198,3079,2795,284,5007,4410,597,3586,3229,357
14,1002360222,Blue,Middle,Jensen,Cloud9,LeBlanc,Tristana,Sejuani,Kalista,Trundle,...,8.297521,3183,2408,775,5215,4134,1081,4483,3561,922
15,1002360222,Blue,ADC,Sneaky,Cloud9,Xayah,Tristana,Sejuani,Kalista,Trundle,...,9.752066,3214,3122,92,4954,4977,-23,3190,2904,286
16,1002360222,Blue,Support,Smoothie,Cloud9,Rakan,Tristana,Sejuani,Kalista,Trundle,...,0.429752,1997,2728,-731,3134,4120,-986,2452,2669,-217
17,1002360222,Red,Top,VVvert,Team oNe Esports,Gnar,Elise,Thresh,Syndra,Orianna,...,8.528926,3187,3000,187,4534,4852,-318,4695,4534,161
18,1002360222,Red,Jungle,4LaN,Team oNe Esports,Nidalee,Elise,Thresh,Syndra,Orianna,...,4.396694,2795,3079,-284,4410,5007,-597,3229,3586,-357
19,1002360222,Red,Middle,Brucer,Team oNe Esports,Lucian,Elise,Thresh,Syndra,Orianna,...,7.206612,2408,3183,-775,4134,5215,-1081,3561,4483,-922
20,1002360222,Red,ADC,Absolut,Team oNe Esports,Kog'Maw,Elise,Thresh,Syndra,Orianna,...,9.223140,3122,3214,-92,4977,4954,23,2904,3190,-286
21,1002360222,Red,Support,RedBert,Team oNe Esports,Morgana,Elise,Thresh,Syndra,Orianna,...,1.223140,2728,1997,731,4120,3134,986,2669,2452,217
24,1002360229,Blue,Top,PvPStejos,Gambit Esports,Camille,Lucian,Galio,Alistar,Syndra,...,8.657014,3075,3048,27,4335,4639,-304,4365,4669,-304
25,1002360229,Blue,Jungle,Diamondprox,Gambit Esports,Gragas,Lucian,Galio,Alistar,Syndra,...,4.792811,2891,3207,-316,4318,4622,-304,3180,3081,99
26,1002360229,Blue,Middle,Kira,Gambit Esports,Ryze,Lucian,Galio,Alistar,Syndra,...,8.746880,3251,3432,-181,5029,5605,-576,4626,4917,-291
27,1002360229,Blue,ADC,Blasting,Gambit Esports,Xayah,Lucian,Galio,Alistar,Syndra,...,8.776835,3049,2901,148,4655,5331,-676,3099,3103,-4
28,1002360229,Blue,Support,EDward,Gambit Esports,Rakan,Lucian,Galio,Alistar,Syndra,...,0.748877,2072,2152,-80,3052,3385,-333,3069,2691,378
29,1002360229,Red,Top,Jirall,Lyon Gaming,Jax,Sejuani,Cassiopeia,Kalista,Kayn,...,9.076385,3048,3075,-27,4639,4335,304,4669,4365,304
30,1002360229,Red,Jungle,Oddie,Lyon Gaming,Maokai,Sejuani,Cassiopeia,Kalista,Kayn,...,4.283575,3207,2891,316,4622,4318,304,3081,3180,-99
31,1002360229,Red,Middle,Seiya,Lyon Gaming,Jayce,Sejuani,Cassiopeia,Kalista,Kayn,...,9.405891,3432,3251,181,5605,5029,576,4917,4626,291
32,1002360229,Red,ADC,WhiteLotus,Lyon Gaming,Tristana,Sejuani,Cassiopeia,Kalista,Kayn,...,9.585622,2901,3049,-148,5331,4655,676,3103,3099,4
33,1002360229,Red,Support,Genthix,Lyon Gaming,Braum,Sejuani,Cassiopeia,Kalista,Kayn,...,1.587619,2152,2072,80,3385,3052,333,2691,3069,-378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1392,1002320090,Blue,Top,CuVee,Samsung Galaxy,Kennen,Jayce,Rakan,Sejuani,Syndra,...,11.368703,3397,2960,437,5238,4568,670,4934,4522,412
1393,1002320090,Blue,Jungle,Ambition,Samsung Galaxy,Zac,Jayce,Rakan,Sejuani,Syndra,...,4.413732,3243,2791,452,4792,4120,672,3830,2968,862
1394,1002320090,Blue,Middle,Crown,Samsung Galaxy,Malzahar,Jayce,Rakan,Sejuani,Syndra,...,9.603210,3114,3342,-228,4914,5407,-493,4792,4716,76
1395,1002320090,Blue,ADC,Ruler,Samsung Galaxy,Xayah,Jayce,Rakan,Sejuani,Syndra,...,10.994204,3181,3298,-117,5395,4940,455,3222,2921,301
1396,1002320090,Blue,Support,CoreJJ,Samsung Galaxy,Janna,Jayce,Rakan,Sejuani,Syndra,...,0.534998,2285,2368,-83,3874,3447,427,2703,2928,-225
1397,1002320090,Red,Top,Huni,SK Telecom T1,Gnar,Kalista,Tristana,Galio,Jarvan IV,...,9.763709,2960,3397,-437,4568,5238,-670,4522,4934,-412
1398,1002320090,Red,Jungle,Peanut,SK Telecom T1,Gragas,Kalista,Tristana,Galio,Jarvan IV,...,3.771734,2791,3243,-452,4120,4792,-672,2968,3830,-862
1399,1002320090,Red,Middle,Faker,SK Telecom T1,Cassiopeia,Kalista,Tristana,Galio,Jarvan IV,...,10.646456,3342,3114,228,5407,4914,493,4716,4792,-76
1400,1002320090,Red,ADC,Bang,SK Telecom T1,Varus,Kalista,Tristana,Galio,Jarvan IV,...,10.111458,3298,3181,117,4940,5395,-455,2921,3222,-301
1401,1002320090,Red,Support,Wolf,SK Telecom T1,Lulu,Kalista,Tristana,Galio,Jarvan IV,...,0.454748,2368,2285,83,3447,3874,-427,2928,2703,225
1404,1002320097,Blue,Top,CuVee,Samsung Galaxy,Gnar,Jayce,Rakan,Sejuani,Syndra,...,8.917749,2833,2994,-161,4744,4587,157,3930,3975,-45
1405,1002320097,Blue,Jungle,Ambition,Samsung Galaxy,Jarvan IV,Jayce,Rakan,Sejuani,Syndra,...,4.415584,2775,2615,160,4125,4057,68,3322,3384,-62
1406,1002320097,Blue,Middle,Crown,Samsung Galaxy,Malzahar,Jayce,Rakan,Sejuani,Syndra,...,9.379509,2909,3863,-954,4750,5894,-1144,4344,4826,-482
1407,1002320097,Blue,ADC,Ruler,Samsung Galaxy,Xayah,Jayce,Rakan,Sejuani,Syndra,...,9.870130,3155,3358,-203,4799,5136,-337,3146,3133,13
1408,1002320097,Blue,Support,CoreJJ,Samsung Galaxy,Janna,Jayce,Rakan,Sejuani,Syndra,...,0.288600,2253,2395,-142,3475,3573,-98,2911,3045,-134
1409,1002320097,Red,Top,Huni,SK Telecom T1,Yasuo,Kalista,Tristana,Galio,Shen,...,10.303030,2994,2833,161,4587,4744,-157,3975,3930,45
1410,1002320097,Red,Jungle,Peanut,SK Telecom T1,Gragas,Kalista,Tristana,Galio,Shen,...,3.463203,2615,2775,-160,4057,4125,-68,3384,3322,62
1411,1002320097,Red,Middle,Faker,SK Telecom T1,Ryze,Kalista,Tristana,Galio,Shen,...,10.591631,3863,2909,954,5894,4750,1144,4826,4344,482
1412,1002320097,Red,ADC,Bang,SK Telecom T1,Varus,Kalista,Tristana,Galio,Shen,...,8.715729,3358,3155,203,5136,4799,337,3133,3146,-13
1413,1002320097,Red,Support,Wolf,SK Telecom T1,Lulu,Kalista,Tristana,Galio,Shen,...,0.461760,2395,2253,142,3573,3475,98,3045,2911,134
1416,1002320098,Blue,Top,CuVee,Samsung Galaxy,Cho'gath,Jayce,Rakan,Kassadin,Taliyah,...,6.741016,2674,4207,-1533,4453,6584,-2131,3814,4060,-246
1417,1002320098,Blue,Jungle,Ambition,Samsung Galaxy,Sejuani,Jayce,Rakan,Kassadin,Taliyah,...,4.436183,2985,3118,-133,4992,4796,196,3456,3550,-94
1418,1002320098,Blue,Middle,Crown,Samsung Galaxy,Malzahar,Jayce,Rakan,Kassadin,Taliyah,...,8.029740,3307,3609,-302,5302,5465,-163,4947,4949,-2
1419,1002320098,Blue,ADC,Ruler,Samsung Galaxy,Varus,Jayce,Rakan,Kassadin,Taliyah,...,9.690211,3390,2846,544,5390,5056,334,3308,2636,672
1420,1002320098,Blue,Support,CoreJJ,Samsung Galaxy,Lulu,Jayce,Rakan,Kassadin,Taliyah,...,0.470880,2093,1954,139,3610,3017,593,2782,2544,238
1421,1002320098,Red,Top,Huni,SK Telecom T1,Trundle,Kalista,Janna,Galio,Shen,...,9.169765,4207,2674,1533,6584,4453,2131,4060,3814,246
1422,1002320098,Red,Jungle,Blank,SK Telecom T1,Gragas,Kalista,Janna,Galio,Shen,...,3.444857,3118,2985,133,4796,4992,-196,3550,3456,94
1423,1002320098,Red,Middle,Faker,SK Telecom T1,Karma,Kalista,Janna,Galio,Shen,...,8.252788,3609,3307,302,5465,5302,163,4949,4947,2
1424,1002320098,Red,ADC,Bang,SK Telecom T1,Tristana,Kalista,Janna,Galio,Shen,...,8.599752,2846,3390,-544,5056,5390,-334,2636,3308,-672
1425,1002320098,Red,Support,Wolf,SK Telecom T1,Leona,Kalista,Janna,Galio,Shen,...,1.115242,1954,2093,-139,3017,3610,-593,2544,2782,-238

In [16]:
# Lets check agian to see if any null values
player_data.isnull().any()

gameid                     False
url                        False
league                     False
split                      False
date                       False
week                       False
game                       False
patchno                    False
playerid                   False
side                       False
position                   False
player                     False
team                       False
champion                   False
ban1                       False
ban2                       False
ban3                       False
ban4                       False
ban5                       False
gamelength                 False
result                     False
k                          False
d                          False
a                          False
teamkills                  False
teamdeaths                 False
doubles                    False
triples                    False
quadras                    False
pentas                     False
                           ...
dmgtochampsperminute       False
dmgshare                   False
earnedgoldshare            False
wards                      False
wpm                        False
wardshare                  False
wardkills                  False
wcpm                       False
visionwards                False
visionwardbuys             False
visiblewardclearrate       False
invisiblewardclearrate     False
totalgold                  False
earnedgpm                  False
goldspent                  False
gspd                       False
minionkills                False
monsterkills               False
monsterkillsownjungle      False
monsterkillsenemyjungle    False
cspm                       False
goldat10                   False
oppgoldat10                False
gdat10                     False
goldat15                   False
oppgoldat15                False
gdat15                     False
xpat10                     False
oppxpat10                  False
xpdat10                    False
Length: 92, dtype: bool

In [17]:
# Fill null values with -1 for not taken

Object `grep` not found.