In [1]:
# Here we are going to look at the Role position from worlds
# This will follow the same template as my mid analysis but only looking
# at gdat10 and gdat15 
import pandas as pd
import numpy as np
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as offline

offline.init_notebook_mode(connected = True)

In [2]:
player_data = pd.read_csv('../Data/Player_specific_data.csv')
player_data.head()

,gameid,position,player,team,champion,ban1,ban2,ban3,ban4,ban5,...,cspm,goldat10,oppgoldat10,gdat10,goldat15,oppgoldat15,gdat15,xpat10,oppxpat10,xpdat10
0,1002390182,Top,Letme,Royal Never Give Up,Cho'gath,Gragas,Xayah,Alistar,Taliyah,Lucian,...,8.748387,3114,3225,-111,4986,4903,83,4493,4817,-324
1,1002390182,Jungle,Mlxg,Royal Never Give Up,Rek'Sai,Gragas,Xayah,Alistar,Taliyah,Lucian,...,4.748387,2944,3560,-616,5052,5266,-214,3378,3686,-308
2,1002390182,Middle,Xiaohu,Royal Never Give Up,Ryze,Gragas,Xayah,Alistar,Taliyah,Lucian,...,9.341935,3113,3623,-510,5275,5322,-47,4478,5053,-575
3,1002390182,ADC,Uzi,Royal Never Give Up,Kog'Maw,Gragas,Xayah,Alistar,Taliyah,Lucian,...,10.348387,3035,3205,-170,4884,5105,-221,3192,3336,-144
4,1002390182,Support,Ming,Royal Never Give Up,Janna,Gragas,Xayah,Alistar,Taliyah,Lucian,...,0.258065,2279,2307,-28,3528,3403,125,2742,2795,-53

In [3]:
#Getting only Role players
Role_mask = player_data['position'] == 'Role'
Roles = player_data[Role_mask]
Roles.head()

,gameid,position,player,team,champion,ban1,ban2,ban3,ban4,ban5,...,cspm,goldat10,oppgoldat10,gdat10,goldat15,oppgoldat15,gdat15,xpat10,oppxpat10,xpdat10
0,1002390182,Top,Letme,Royal Never Give Up,Cho'gath,Gragas,Xayah,Alistar,Taliyah,Lucian,...,8.748387,3114,3225,-111,4986,4903,83,4493,4817,-324
5,1002390182,Top,Thaldrin,Fenerbahce Esports,Maokai,Kalista,Jarvan IV,Sejuani,Shen,Galio,...,8.051613,3225,3114,111,4903,4986,-83,4817,4493,324
10,1002390191,Top,Expect,G2 Esports,Shen,Jarvan IV,Janna,Lulu,Ryze,Syndra,...,9.150090,3332,3046,286,4888,4874,14,4258,4200,58
15,1002390191,Top,CuVee,Samsung Galaxy,Cho'gath,Kalista,Sejuani,Rakan,LeBlanc,Kassadin,...,10.198915,3046,3332,-286,4874,4888,-14,4200,4258,-58
20,1002390201,Top,Khan,Longzhu Gaming,Jarvan IV,Kog'Maw,Janna,Xayah,Renekton,Shen,...,8.585691,3089,3037,52,5009,5289,-280,4332,4463,-131

In [4]:
# Lets group people together
Role_stats = Roles.groupby(by ='player').describe()
Role_stats

             a                                                      airdrakes  \
         count       mean       std   min    25%   50%    75%   max     count
player
957        6.0   4.500000  1.516575   2.0   4.00   4.5   5.75   6.0       6.0
Alphari    6.0   5.166667  4.490731   0.0   1.50   5.0   8.50  11.0       6.0
Archie     6.0   4.666667  4.760952   0.0   1.50   3.0   7.50  12.0       6.0
CuVee      6.0   3.833333  3.188521   0.0   1.00   4.5   6.50   7.0       6.0
Expect     6.0   4.000000  3.521363   0.0   2.25   3.0   5.25  10.0       6.0
Flame      6.0   4.833333  1.940790   3.0   3.25   4.5   5.75   8.0       6.0
Hauntzer   6.0   3.833333  4.792355   0.0   0.75   3.0   3.75  13.0       6.0
Huni       6.0   4.833333  2.926887   1.0   2.75   5.5   6.00   9.0       6.0
Impact     6.0   5.000000  1.673320   3.0   4.00   4.5   6.50   7.0       6.0
Khan       5.0   6.600000  5.770615   0.0   3.00   6.0   9.00  15.0       5.0
Letme      6.0   5.166667  3.763863   0.0   3.25   5.0   6.75  11.0       6.0
MMD        6.0   1.833333  2.136976   0.0   1.00   1.0   1.75   6.0       6.0
Mouse      6.0   6.333333  4.457204   2.0   3.00   5.0   9.25  13.0       6.0
Rascal     1.0  14.000000       NaN  14.0  14.00  14.0  14.00  14.0       1.0
Thaldrin   6.0   2.000000  2.756810   0.0   0.00   1.0   2.75   7.0       6.0
Ziv        6.0   3.666667  3.932768   0.0   0.50   2.5   6.75   9.0       6.0
sOAZ       6.0   3.333333  3.265986   0.0   1.25   2.5   4.50   9.0       6.0

                     ...     xpat10         xpdat10                          \
              mean   ...        75%     max   count        mean         std
player               ...
957       0.166667   ...    4720.75  4980.0     6.0   15.000000  400.860574
Alphari   0.000000   ...    4691.00  4929.0     6.0   63.500000  332.982132
Archie    0.000000   ...    4002.50  4838.0     6.0 -366.166667  441.543392
CuVee     0.000000   ...    4708.75  4941.0     6.0  279.500000  590.373356
Expect    0.166667   ...    4794.50  5169.0     6.0   67.000000  463.943962
Flame     0.000000   ...    4552.00  4788.0     6.0   88.333333  482.077034
Hauntzer  0.000000   ...    4774.25  4846.0     6.0  -35.333333  544.646552
Huni      0.333333   ...    4945.00  5110.0     6.0  226.333333  285.278577
Impact    0.000000   ...    4718.75  5091.0     6.0  144.666667  610.719794
Khan      0.000000   ...    4478.00  4581.0     5.0  268.600000  476.574548
Letme     0.166667   ...    4603.25  4654.0     6.0  -38.833333  478.512870
MMD       0.000000   ...    4565.50  4736.0     6.0  -43.166667  547.803036
Mouse     0.000000   ...    4598.00  4736.0     6.0 -440.833333  477.308880
Rascal    0.000000   ...    4471.00  4471.0     1.0  243.000000         NaN
Thaldrin  0.166667   ...    4758.25  4817.0     6.0 -307.666667  574.474601
Ziv       0.166667   ...    4833.75  4946.0     6.0   69.833333  307.861928
sOAZ      0.166667   ...    4630.75  4787.0     6.0   13.500000  565.514544


             min     25%    50%     75%     max
player
957       -442.0 -240.50  -63.0  211.25   655.0
Alphari   -414.0 -182.75  215.0  288.00   368.0
Archie    -809.0 -721.00 -421.5 -113.00   286.0
CuVee     -450.0  -51.50  134.5  645.25  1156.0
Expect    -500.0 -234.25   12.0  323.50   767.0
Flame     -286.0 -226.25  -38.5  123.00  1005.0
Hauntzer  -973.0 -253.75  136.5  356.50   442.0
Huni        27.0   60.50   77.0  298.25   750.0
Impact    -391.0 -310.25  -74.0  511.75  1089.0
Khan      -206.0 -131.00  139.0  732.00   809.0
Letme     -760.0 -276.25  -49.5  346.00   500.0
MMD       -655.0 -255.25 -167.5  -10.00   973.0
Mouse    -1089.0 -738.00 -457.0  -73.25   135.0
Rascal     243.0  243.00  243.0  243.00   243.0
Thaldrin -1156.0 -678.25 -190.0  107.75   324.0
Ziv       -368.0 -117.50   73.5  341.00   391.0
sOAZ     -1005.0  -65.50  165.5  198.50   688.0

[17 rows x 576 columns]

In [5]:
# Have to get the avg stats only 
Role_stats_avg = Role_stats.iloc[:,Role_stats.columns.get_level_values(1) == 'mean']
Role_stats_avg.columns = Role_stats_avg.columns.droplevel(1)
Role_stats_avg.head()

,a,airdrakes,ckpm,cspm,d,dmgshare,dmgtochamps,dmgtochampsperminute,doubles,earnedgoldshare,...,visionwardbuys,visionwards,wardkills,wards,wardshare,waterdrakes,wcpm,wpm,xpat10,xpdat10
player,,,,,,,,,,,,,,,,,,,,,
957,4.500000,0.166667,0.535552,7.783044,1.000000,0.199292,13481.333333,430.435716,0.333333,0.186111,...,3.333333,2.666667,2.333333,16.666667,0.159610,0.166667,0.075412,0.524714,4620.166667,15.000000
Alphari,5.166667,0.000000,0.451350,8.426038,2.000000,0.183989,13233.833333,331.250502,0.000000,0.201007,...,4.833333,4.500000,5.500000,24.000000,0.151853,0.000000,0.131354,0.586183,4566.000000,63.500000
Archie,4.666667,0.000000,0.798887,6.739515,5.000000,0.155573,10048.333333,296.646165,0.000000,0.183813,...,4.333333,3.666667,4.333333,15.666667,0.153299,0.000000,0.119422,0.479833,3603.333333,-366.166667
CuVee,3.833333,0.000000,0.450246,9.643818,1.333333,0.229787,15045.166667,407.187175,0.000000,0.220352,...,8.000000,7.166667,8.333333,24.000000,0.172445,0.500000,0.213759,0.655803,4559.500000,279.500000
Expect,4.000000,0.166667,0.443927,8.290951,1.666667,0.198628,16598.166667,411.857379,0.166667,0.201765,...,5.166667,4.166667,5.500000,19.500000,0.151265,0.166667,0.147931,0.504470,4574.333333,67.000000

In [6]:
# Lets graph the gdat10 and gdat15 
temp_sort = Role_stats_avg.sort_values(by = 'Var1')
var1 = list(temp_sort['Var1'].values)
var2 = list(temp_sort['Var2'].values)
players = list(temp_sort.index)

trace1 = go.Bar(x = players, y = var1, name = 'Var1')
trace2 = go.Bar(x = players, y = var2, name = 'Var2')

data = [trace1,trace2]
layout = go.Layout(barmode = 'grouped',
                  title = 'Average Role Var1 vs. Var2',
                  yaxis = dict(title = 'Var1'),
                  xaxis = dict(tickangle = 90)
                  )

fig = go.Figure(data = data, layout = layout)

#offline.plot(fig, filename ='Final_Var1_vs_Var2_Diff.html')

'file:///Users/NicholasRoller/Documents/Worlds Analysis/Role Analysis/Final_Top_Gold_Diff.html'